# Reset dog food alarm
- alias: "Dog Food Activate"
  trigger:
    - platform: time
      after: '01:00:00'
    - platform: time
      after: '16:00:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dog_needs_food

# Dog is fed
- alias: "Dog Food Reset"
  trigger:
    - platform: state
      entity_id: binary_sensor.dog_food_bin
      to: "on"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.dog_needs_food

# Remind to feed dog after time threshold or front/garage door opening
- alias: "Dog Food Alert"
  trigger:
    - platform: time
      after: '07:30:00'
    - platform: time
      after: '18:00:00'
  action:
    - service: notify.patrick_iphone
      data:
        message: "Don't forget to feed Paisley!"

# Turn on downstairs lamp in the morning
- alias: "Lamp Auto On"
  trigger:
    - platform: state
      entity_id: binary_sensor.entry_motion
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: time
        after: '04:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.downstairs_lamp
        brightness: 200
        transition: 10
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.lamp_auto_on

- alias: "Lamp Auto Off"
  trigger:
    - platform: sun
      event: sunrise
      offset: '00:30:00'
  condition:
    condition: state
    entity_id: input_boolean.lamp_auto_on
    state: "on"
  action:
    - service: light.turn_off
      data:
        entity_id: light.downstairs_lamp
