homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 152
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Other customizations and stuff
  customize: !include customize.yaml

frontend:

config:

http:
  base_url: !secret hass_base_url
  api_password: !secret hass_password
  use_x_forwarded_for: true
  ip_ban_enabled: false
  login_attempts_threshold: 5

# MQTT Broker
mqtt:
  broker: localhost
  username: !secret mqtt_user
  password: !secret mqtt_pass

# include a bunch of stuff to make this file cleaner
group: !include_dir_merge_named groups
switch: !include_dir_list switches
camera: !include_dir_list cameras
cover: !include_dir_list covers
binary_sensor: !include_dir_list binary_sensors
sensor: !include_dir_list sensors
light: !include_dir_list lights
media_player: !include_dir_list media
input_boolean: !include_dir_named input_bool
#input_select: !include_dir_named input_select
automation: !include_dir_list automation
scene: !include_dir_list scenes

# Speech Intents
alexa:
intent_script: !include_dir_named intents

#IFTTT
ifttt:
  key: !secret ifttt_key

# ecobee
ecobee:
  api_key: !secret ecobee_api_key

# Hue
hue:
  bridges:
    - host: !secret hue_hostname
      allow_unreachable: true
      allow_hue_groups: false

# Push notifications
notify:
  - name: downstairs_tv
    platform: webostv
    host: !secret living_room_tv_host
  - name: phones
    platform: group
    services:
      - service: ios_speiphone
      - service: ios_courtneys_iphone


# z-wave
zwave:
  usb_path: /dev/zwave
  device_config: !include zwave_devices.yaml

# zigbee home automation
zha:
  usb_path: /dev/zigbee
  database_path: /home/hass/.homeassistant/zigbee.db

# zones
zone:
  - name: Home
    icon: mdi:home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 150
  - name: Red Hat
    icon: mdi:briefcase
    latitude: 35.775267
    longitude: -78.637566
    radius: 150

# show the map
map:

# recorder
recorder:
  db_url: !secret mysql_connection
  purge_interval: 1
  purge_keep_days: 7
  exclude:
    entities:
      - sun.sun
      - sensor.pws_feelslike_string
      - sensor.pws_precip_today_in
      - sensor.pws_precip_today_string
      - sensor.pws_relative_humidity
      - sensor.pws_temperature_string
      - sensor.pws_temp_f
      - sensor.pws_UV
      - sensor.pws_weather
      - sensor.pws_wind_dir
      - sensor.pws_wind_mph
      - sensor.pws_wind_string
    domains:
      - group
      - zwave

# text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key
    aws_secret_access_key: !secret aws_secret_key
    region_name: us-east-1
    voice: Joanna

# ios app
ios:

# logger
logger:
  default: warning

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
