homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 35.740
  longitude: -78.851
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 152
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Other customizations and stuff
  customize: !include customize.yaml

frontend:

http:
  api_password: !secret hass_password

device_tracker:
  - platform: owntracks
    devices:
      patrick_iphone: /owntracks/patrick/spe-iphone
  - platform: owntracks
    devices:
      patrick_iphone: /owntracks/courtney/courtney-iphone

# SmartThings MQTT Bridge
mqtt:
  broker: localhost
  username: !secret mqtt_user
  password: !secret mqtt_pass

# include a bunch of stuff to make this file cleaner
group: !include_dir_merge_named groups
switch: !include_dir_list switches
climate: !include_dir_list climate
binary_sensor: !include_dir_list binary_sensors
sensor: !include_dir_list sensors
light: !include_dir_list lights
media_player: !include_dir_list media
input_boolean: !include_dir_named input_bool
input_select: !include_dir_named input_select
automation: !include_dir_list automation

# Advertise Hue
emulated_hue:
  exposed_domains:
    - switch
    - light
    - group
    - media_player
    - input_boolean
    - fan
    - cover

# Push notifications
notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# z-wave
zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_devices.yaml

# zigbee home automation
#zha:
#  usb_path: /dev/ttyUSB1
#  database_path: /home/hass/.homeassistant/zigbee.db

# recorder
recorder:
  db_url: !secret mysql_connection
  purge_days: 7

# logger
logger:
  default: warning

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
