homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 152
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

frontend:

config:

http:
  base_url: !secret hass_base_url
  api_password: !secret hass_password
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_networks
  ip_ban_enabled: false
  login_attempts_threshold: 5

# MQTT Broker
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass

# include a bunch of stuff to make this file cleaner
group: !include_dir_merge_named groups
switch: !include_dir_list switches
binary_sensor: !include_dir_list binary_sensors
sensor: !include_dir_list sensors
light: !include_dir_list lights
media_player: !include_dir_list media
automation: !include_dir_list automation
scene: !include_dir_list scenes

# Speech Intents
alexa:
#intent_script: !include_dir_named intents

#IFTTT
ifttt:
  key: !secret ifttt_key

# Location data
device_tracker:
  - platform: gpslogger

# ecobee
ecobee:
  api_key: !secret ecobee_api_key

# Hue
hue:
  bridges:
    - host: !secret hue_hostname
      allow_unreachable: true
      allow_hue_groups: false

# Push notifications
notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_server_key
    gcm_sender_id: !secret gcm_sender_id
  - name: downstairs_tv
    platform: webostv
    host: !secret living_room_tv_host
  - name: phones
    platform: group
    services:
      - service: ios_courtneys_iphone
      - service: html5_patrick_phone


# z-wave
zwave:
  usb_path: /dev/zwave
  device_config: !include zwave_devices.yaml

# zigbee home automation
zha:
  usb_path: /dev/zigbee
  database_path: /config/zigbee.db

# zones
zone:
  - name: Home
    icon: mdi:home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 150
  - name: Red Hat
    icon: mdi:briefcase
    latitude: 35.775267
    longitude: -78.637566
    radius: 150

# show the map
map:

# recorder
recorder:
  db_url: !secret mysql_connection
  purge_interval: 1
  purge_keep_days: 7
  exclude:
    entities:
      - sun.sun
      - sensor.pws_feelslike_string
      - sensor.pws_precip_today_in
      - sensor.pws_precip_today_string
      - sensor.pws_relative_humidity
      - sensor.pws_temperature_string
      - sensor.pws_temp_f
      - sensor.pws_UV
      - sensor.pws_weather
      - sensor.pws_wind_dir
      - sensor.pws_wind_mph
      - sensor.pws_wind_string
      - sensor.pws_precip_1d
      - sensor.pws_weather_1h
      - sensor.pws_weather_2h
      - sensor.pws_weather_3h
      - sensor.pws_weather_4h
      - sensor.pws_weather_5h
      - sensor.pws_weather_6h
      - sensor.pws_weather_7h
      - sensor.pws_weather_8h
      - sensor.pws_weather_9h
      - sensor.pws_weather_10h
      - sensor.pws_weather_11h
      - sensor.pws_weather_12h
    domains:
      - group
      - zwave

# text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key
    aws_secret_access_key: !secret aws_secret_key
    region_name: us-east-1
    voice: Joanna

# ios app
ios:

# logger
logger:
  default: warning

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
