# Master Bedroom Fan
- platform: mqtt
  name: "Bedroom Fan"
  retain: true
  state_topic: "smartthings/Master Bedroom Fan/switch"
  command_topic: "smartthings/Master Bedroom Fan/switch"
  speed_state_topic: "smartthings/Master Bedroom Fan/switch"
  speed_command_topic: "smartthings/Master Bedroom Fan/switch"
  payload_on: "on"
  payload_off: "off"
  speeds: [ low, med, high ]
  payload_low_speed: "8"
  payload_medium_speed: "67"
  payload_high_speed: "99"
