# Google Cast
- platform: cast

# TV
- platform: webostv
  name: "Living Room TV"
  host: !secret living_room_tv_host
  mac: !secret living_room_tv_mac

# Apple TV
- platform: apple_tv
  name: "Apple TV"
  host: !secret atv_host
  login_id: !secret atv_login
