# z-wave sensors

# Climate
- platform: mqtt
  state_topic: 'smartthings/Crawl Space Multi-sensor/temperature'
  name: 'Crawl Space Temperature'
  unit_of_measurement: '°F'

- platform: mqtt
  state_topic: 'smartthings/Crawl Space Multi-sensor/humidity'
  name: 'Crawl Space Humidity'
  unit_of_measurement: '%'

# nodemcu status
- platform: mqtt
  state_topic: 'pat/alarm/status'
  name: 'Alarm Sensor Status'

# battery levels
- platform: mqtt
  state_topic: 'smartthings/Crawl Space Multi-sensor/battery'
  name: 'Crawl Space Multi-sensor battery'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: 'smartthings/Crawl Space Door/battery'
  name: 'Crawl Space Door battery'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: 'smartthings/Dog Food Sensor/battery'
  name: 'Dog Food Bin battery'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: 'smartthings/HVAC Leak Detector/battery'
  name: 'HVAC Leak Detector battery'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: 'smartthings/Water Heater Leak Detector/battery'
  name: 'Water Heater Leak Detector battery'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: 'smartthings/Upstairs Hall Motion/battery'
  name: 'Upstairs Hall Motion battery'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: 'smartthings/Entry Motion/battery'
  name: 'Entry Motion battery'
  unit_of_measurement: '%'

#
# weather stuff
- platform: yr
#  - platform: wunderground
#    api_key: !secret wunderground_api_key
#    pws_id: KNCAPEX32
#    monitored_conditions:
#      - alerts
#      - dewpoint_f
#      - dewpoint_string
#      - feelslike_f
#      - feelslike_string
#      - heat_index_f
#      - heat_index_string
#      - elevation
#      - location
#      - observation_time
#      - precip_1hr_in
#      - precip_1hr_metric
#      - precip_1hr_string
#      - precip_today_in
#      - precip_today_metric
#      - precip_today_string
#      - pressure_in
#      - pressure_mb
#      - pressure_trend
#      - relative_humidity
#      - station_id
#      - solarradiation
#      - temperature_string
#      - temp_f
#      - UV
#      - visibility_mi
#      - weather
#      - wind_degrees
#      - wind_dir
#      - wind_gust_mph
#      - wind_mph
#      - wind_string
