alias: "Downstairs Fan Input"
trigger:
  - platform: state
    entity_id: input_select.downstairs_fan
action:
  - service: light.turn_on
    data_template:
      entity_id: light.downstairs_fan_level_2_0
      brightness: >
        {% if is_state('input_select.downstairs_fan', 'High')  %}
        250
        {% elif is_state('input_select.downstairs_fan', 'Medium')  %}
        100
        {% elif is_state('input_select.downstairs_fan', 'Low')  %}
        50
        {% else %}
        0
        {% endif %}
