alias: "Downstairs Fan Wall Switch"
trigger:
  - platform: state
    entity_id: light.downstairs_fan_level_2_0
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.downstairs_fan
      option: >
        {% if is_state('light.downstairs_fan_level_2_0', 'off')  %}
        Off
        {% elif states.light.downstairs_fan_level_2_0.attributes.brightness >= 176  %}
        High
        {% elif states.light.downstairs_fan_level_2_0.attributes.brightness >= 88  %}
        Medium
        {% else %}
        Low
        {% endif %}
