alias: "Master Bedroom Fan Input"
trigger:
  - platform: state
    entity_id: input_select.master_fan
action:
  - service: light.turn_on
    data_template:
      entity_id: light.master_bedroom_fan_level_8_0
      brightness: >
        {% if is_state('input_select.master_fan', 'High')  %}
        250
        {% elif is_state('input_select.master_fan', 'Medium')  %}
        100
        {% elif is_state('input_select.master_fan', 'Low')  %}
        50
        {% else %}
        0
        {% endif %}
