alias: "Master Fan Wall Switch"
trigger:
  - platform: state
    entity_id: light.master_bedroom_fan_level_8_0
action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.master_fan
      option: >
        {% if is_state('light.master_bedroom_fan_level_8_0', 'off')  %}
        Off
        {% elif states.light.master_bedroom_fan_level_8_0.attributes.brightness >= 176  %}
        High
        {% elif states.light.master_bedroom_fan_level_8_0.attributes.brightness >= 88  %}
        Medium
        {% else %}
        Low
        {% endif %}
