alias: "Dog Food Alert"
trigger:
  - platform: time
    at: '07:30:00'
  - platform: time
    at: '18:00:00'
condition:
  condition: state
  entity_id: input_boolean.dog_needs_food
  state: "on"
action:
  - service: notify.phones
    data:
      message: "Don't forget to feed Paisley!"
