# Dog has been fed
alias: "Dog Food Reset"
trigger:
  - platform: state
    entity_id: binary_sensor.dog_food_bin_sensor
    to: "on"
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.dog_needs_food
