alias: "Nursery Auto Off"
trigger:
  - platform: state
    entity_id: sensor.nursery_multi_burglar
    to: "0"
    for:
      minutes: 5
condition:
  condition: state
  entity_id: input_boolean.nursery_auto_on
  state: "on"
action:
  - service: light.turn_off
    data:
      entity_id: group.nursery
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.nursery_auto_on
