alias: "Living Room Double Tap On"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 1
      scene_data: 3
action:
  - service: scene.turn_on
    data:
      entity_id: scene.downstairs_night_lights
