alias: "Living Room Double Tap Off"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 2
      scene_data: 3
action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.living_room
