alias: "Living Room Triple Tap On"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 1
      scene_data: 4
action:
  - service: light.turn_on
    data:
      entity_id: light.downstairs_lamp
      brightness: 200
  - service: light.turn_on
    data:
      entity_id: light.downstairs_fan_light_level
      brightness: 255
