alias: "Living Room Triple Tap Off"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.downstairs_fan_light
      scene_id: 2
      scene_data: 4
action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - group.view_downstairs
        - group.exterior_lights
        - group.kitchen
