alias: "Bathroom Double Tap Off"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.master_bathroom_vanity_lights
      scene_id: 2
      scene_data: 3
action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.master_bathroom
