alias: "Lamp Auto On"
trigger:
  - platform: state
    entity_id: binary_sensor.stairs_motion_sensor
    to: "on"
condition:
  condition: and
  conditions:
    - condition: sun
      before: sunrise
    - condition: time
      after: '04:30:00'
action:
  - service: light.turn_on
    data:
      entity_id: light.downstairs_lamp
      brightness: 200
      transition: 10
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.lamp_auto_on
