alias: "Kitchen Double Tap Off"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_table_light
      scene_id: 2
      scene_data: 3
action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen_under_cabinet
