alias: "Kitchen Triple Tap On"
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.kitchen_table_light
      scene_id: 1
      scene_data: 4
action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen_overhead_light_level
      brightness: 180
  - service: light.turn_on
    data:
      entity_id: light.kitchen_table_light_level
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.kitchen_under_cabinet
      brightness: 255
